---
- name: install docker
  apt:
    name: ['docker.io']
    state: present
    install_recommends: False
  tags: drone

- name: add drone user to docker group
  user:
    name: drone
    groups: docker
    append: True
  tags: drone

- name: copy drone-agent config
  template:
    src: agent.conf.j2
    dest: /etc/drone/agent.conf
    mode: "0640"
    group: drone
  notify: restart drone-agent
  tags: drone

- name: copy drone-agent service
  copy:
    src: drone-agent.service
    dest: /etc/systemd/system/drone-agent.service
  tags: drone

- name: copy drone-agent binary
  get_url:
    url: "https://github.com/vlaborie/ansible-role-drone/blob/master/files/drone-agent?raw=true"
    checksum: "sha256:0b1975789394e2523d5107cd4387faece97af331554a2f5dcf4a7dee85ca05a7"
    dest: /usr/local/bin/drone-agent
    mode: "0755"
  notify: restart drone-server
  tags: drone

- name: start and enable drone agent
  systemd:
    name: drone-agent
    state: started
    daemon-reload: True
    enabled: True
  tags: drone
