---
- name: copy drone-server config
  template:
    src: server.conf.j2
    dest: /etc/drone/server.conf
    mode: "0640"
    group: drone
  notify: restart drone-server
  tags: drone

- name: copy drone-server service
  copy:
    src: drone-server.service
    dest: /etc/systemd/system/drone-server.service
  tags: drone

- name: copy drone-server binary
  get_url:
    url: "https://github.com/vlaborie/ansible-role-drone/blob/master/files/drone-server?raw=true"
    checksum: "sha256:0523dfccea0f2221bc5bb9d12c33248703cbf520a3d091050704e3018a83d64a"
    dest: /usr/local/bin/drone-server
    mode: "0755"
  notify: restart drone-server
  tags: drone

- name: start and enable drone server
  systemd:
    name: drone-server
    state: started
    daemon-reload: True
    enabled: True
  tags: drone
